### ISSUE TITLE
Add configuration option for "time for drive up - late on non-workdays"

### ISSUE THREAD

**Issue by mistergyle** [hvorragend/ha-blueprints#10]
Hi,
I was wondering if there might be an option for a „drive down up late on non-workdays“

Example: kids have to get up latest 7am on workdays but on weekend 8:30 is ok.

see also: https://community.home-assistant.io/t/cover-control-automation-cca-a-comprehensive-and-highly-configurable-roller-blind-blueprint/680539/47

**Comment by mistergyle** [comment]
Thank you 🙏

**Comment by hvorragend** [comment]
Thank you. 

Btw: there are no notifications if you edit a post afterwards.
