### ISSUE TITLE
Wind support

### ISSUE THREAD

**Issue by lejmr** [hvorragend/ha-blueprints#101]
Hi!

I like your plugin and use it for all my windows. I am setting up wind protection for my windows along with this plugin.

I have a sheet from the manufacturer, so according to the window size, I know the maximum wind the sheets can handle. 

Right now, when wind crosses my threshold (a bit lower) than what the manufacturer specifies, I pull them up.

It would be lively to have the option to pull those back when the wind is away.

Right now, I am consuming wind speed from AccuWeather

Thanks!

**Comment by jmerifjKriwe** [comment]
Why not use force action(s) for this?

**Comment by hvorragend** [comment]
Yes, all these features can be implemented using the Force functions: Wind-Protection, Frost-Protection, Rain-Protection. I also mentioned these examples in the beach description. 

The only difference is that it does not revert to the previous status after a force. Here I pass the responsibility to the triggering automation. The wishes are simply too individual.

**Comment by lejmr** [comment]
Thank you!

Can you share any link to documentation? I am new to HA, and I believe anybody would benefit out of that

**Comment by hvorragend** [comment]
Everything is inside the blueprint:

![IMG_3366](https://github.com/hvorragend/ha-blueprints/assets/343705/f0ec8ade-c71e-4506-bc13-32d952fe31a9)

**Comment by lejmr** [comment]
I know, but the question was how to create such an entity. Thanks

**Comment by hvorragend** [comment]
Just create an boolean helper for that. 
https://www.home-assistant.io/integrations/input_boolean/
