### ISSUE TITLE
Bug in is_time_field_enabled

### ISSUE THREAD

**Issue by hvorragend** [hvorragend/ha-blueprints#104]
A small logic error when checking the schedule helper. 

`is_time_field_enabled: "{{ 'time_control_input' in time_control or time_control == [] or time_schedule_helper == [] }}"`

**Comment by Gifford47** [comment]
hey @hvorragend !
this issue leads also to an error that the cover closes although the time field was disabled. have you already a solution?

trace is attached
[trace automation.roll_2024-07-30T14_30_00.125564+00_00.json](https://github.com/user-attachments/files/16430498/trace.automation.roll_2024-07-30T14_30_00.125564%2B00_00.json)
