### ISSUE TITLE
separating temperature and weather condition in the weahter forcast section

### ISSUE THREAD

**Issue by tco99ttocs** [hvorragend/ha-blueprints#108]
Is there a possible in the weather forcast section to separate the weather condition from the temperature?
For example: Use the daily forcast for the temperature but the hourly forcast or the actual value of the condition!

**Comment by hvorragend** [comment]
Sorry, but this is getting too complex for me. The whole issue with the prediction complicates the blueprint anyway and makes support extremely difficult. I don't need to take this any further.
