### ISSUE TITLE
Feature Request: Sun shading optional cover state check

### ISSUE THREAD

**Issue by jimmyhenne** [hvorragend/ha-blueprints#112]
Hi,
I would like to propose an optional setting for sun shading which checks if the cover isn't closed. When the cover is already closed it should not be "opened" to sun shading position.

Background:
For the covers to the east I have set up sun shading starting early in the morning. For weekend days I have set up an additional condition to activate when cover position is above 49. So its activated after I get up and opened the cover manually. But if all start parameters have already been fulfilled, nothing more happens.
So it would be helpful to have that setting in the regular sun shading settings as optional. I would use an entity check to check if the cover isn't closed. I would not check if it is open. Because I sometimes open the covers over night to a little bit and open the windows to use the cooler night temperatures to cool down the rooms. The HA-entity is open but at a current position. Alternatively one can also set a check if the current position is above or under a certain value.

Edit: I have thought about it further. One might experience unwanted behaviour when the cover is completely openend at night. So I think the best solution would be to add a current_position check with an input field to set a value for current_position. Of course everything optional.

**Comment by hvorragend** [comment]
If I am reading this correctly, then it is about the following points:

1)

> I would like to propose an optional setting for sun shading which checks if the cover isn't closed. When the cover is already closed it should not be "opened" to sun shading position.

It has already been checked here whether the roller blind is already closed. This means that no shading should be executed if the blind is closed. 

https://github.com/hvorragend/ha-blueprints/blob/main/blueprints/automation/cover_control_automation.yaml#L2876

2)
You would like to have a configurable value above which shading is permitted. But isn't that automatically and simultaneously the shading position? Below is not possible. See above. 
And an additional configurable value above that doesn't really make sense, does it?

3)
I can't technically take account of fully open roller blinds. This would deactivate the entire shading logic. After all, it should be deliberately and absolutely shaded from this position (100). That is the goal with tags. Here I can only recommend adjusting the shading values. 

Or have I misunderstood something?

**Comment by jimmyhenne** [comment]
> It has already been checked here whether the roller blind is already closed. This means that no shading should be executed if the blind is closed.

I didn't know that it was already taken into account and to be honest I haven't tried 😄 Ouch
I have worked with an additional condition right from the start to sun shade when roller blinds position is above 49.
Will the automation catch up sun shading after opening?

> You would like to have a configurable value above which shading is permitted. But isn't that automatically and simultaneously the shading position?

So far I have set the roller blinds to a manual value in the evening e.g. 30. But that wasn't the exact value which is used for sun shading position. But that could be a thing to try. Thanks

**Comment by hvorragend** [comment]
> Will the automation catch up sun shading after opening?

Yes, if there is a shading trigger coming. 
However, this may well mean that it is not triggered again. See the following note. 

![IMG_4068](https://github.com/user-attachments/assets/f70032c1-273d-49b9-a0c5-b9fd993e01ef)


> Maybe I worded it wrong. I don't mean a cover state check (which is already implemented) but a cover state trigger. So that opening the roller blinds can additionally trigger the automation. Would that be sensible and possible?

If I include the status of the covers in the triggers, there is a ping-pong effect. 
I had originally planned to do this and had already installed it as a test. But the triggers then trigger each other.
