### ISSUE TITLE
Lockout protection while shading

### ISSUE THREAD

**Issue by jhandke** [hvorragend/ha-blueprints#114]
My roller shutter does not open when it is in automatic shading state and the contact sensor for lockout protection is opened. I can not find any trigger for this situation.
Is that the intended behaviour?

However, the prevention of shading when the contact sensor is open works fine.

**Comment by airmaxx** [comment]
I support this function. It is helpful and convenient for patio doors. (I had it before as a manual automation).

Can this be configured with "Additional Condition For Opening The Cover"?

After closing the door, the cover should go back to shading position.

**Comment by cybe** [comment]
Possibly related to #92.

**Comment by hvorragend** [comment]
> My roller shutter does not open when it is in automatic shading state and the contact sensor for lockout protection is opened.

The lockout protection also does not perform any roller blind movements. It is only intended to prevent them. 

Or do you mean the ventilation mode?

**Comment by airmaxx** [comment]
I think @hvorragend is right. Ventilation mode set to something like 95 should do exactly what @jhandke and I were talking about: If the cover is in a shading state, it will open to the ventilation setting (95 in this example) when someone opens the door.

**Comment by hvorragend** [comment]
Do you have any further questions? Then please reply to the closed ticket.
