### ISSUE TITLE
Shutter opening if resident sleeping when shading ends

### ISSUE THREAD

**Issue by holsteiner-kiel** [hvorragend/ha-blueprints#116]
Hi hvorragend,

My problem is while a resident is sleeping, the shutter opens when shading ends. 

My automation:
```
alias: CCA - Schlafzimmer
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.rolladen_schlafzimmer
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_sun_enabled
      - auto_ventilate_enabled
      - auto_shading_enabled
    cover_status_options: cover_helper_enabled
    cover_status_helper: input_text.cca_schlafzimmer
    drive_time: 30
    open_tilt_position: 100
    ventilate_position: 10
    ventilate_tilt_position: 20
    close_tilt_position: 0
    shading_position: 10
    shading_tilt_position: 10
    reset_override_config: reset_timeout
    reset_override_timeout: 30
    drive_delay_random: 10
    contact_sensor: binary_sensor.schlafzimmer_fenster_contact
    shading_brightness_sensor: sensor.helligkeit_sueden_beleuchtungsstarke
    shading_azimuth_start: 135
    shading_azimuth_end: 250
    shading_temperatur_sensor1: sensor.heizung_schlafzimmer_temperatur
    shading_min_temperatur1: 21
    shading_min_temperatur2: 15
    shading_temperatur_sensor2: sensor.hmip_swo_pl_001820c99bd2ce_temperatur
    check_config: true
    resident_sensor: input_boolean.cca_sleeping_schlafzimmer
    individual_config:
      - prevent_shading_end_if_closed
    shading_waitingtime_end: 1200
trace:
  stored_traces: 20
```

My wife works nightshift and is not very happy that it happens. Do you have an idea? Trace of the opening is attached.

Thx,
Markus
[trace automation.cca_schlafzimmer 2024-07-28T15_19_10.267598+00_00.json](https://github.com/user-attachments/files/16404220/trace.automation.cca_schlafzimmer.2024-07-28T15_19_10.267598%2B00_00.json)

**Comment by hvorragend** [comment]
Hi Markus,
I assume you sent me something today, right? Many thanks for that. :-)

I was on holiday for three weeks and didn't spend much time with the blueprint during that time. I'll make up for that. I'll also take a closer look at the resident stuff. So far I have never used resident myself and apparently many users haven't either. It may well be that some things have not yet been taken into account due to the further development of the blueprint.

I'll have a look at this shortly.

**Comment by holsteiner-kiel** [comment]
Dankeschön! Wir können auch gern auf Deutsch schreiben! Ich denke, wir sind
beide deutsche :-)

Ich bin sehr gespannt! Für uns ist resident unabdinglich, weil meine Frau
als Krankenschwester im Schichtdienst arbeitet und teils tagsüber schläft.
Ich hatte vorher ASC auf fhem im Einsatz für das ganze, möchte aber den
fhem in zumindest endlicher Zeit ablösen durch Homeassistant teils mit
NodeRed. Das ASC war halt schon sehr weit entwicklungstechnisch.
Regensensoren, Frostschutz,kompletter Anwesenheitsstatus (Rolläden runter
wenn nicht zu Hause). Das ganze brauche ich gar nicht unbedingt. Die
Residents Funktion für schlafend wäre mir wichtig und 3-state-Sensoren mit
Türöffnung wenn auf offen (in ASC hier das Komfortposition, warum auch
immer). Regen fänd ich noch cool, weil ich eine Klimaanlage im Schlafzimmer
benutze und daher das Fenster auf ist. Wenn bei Regen jetzt der Rolladen
runter fährt auf eine definierte Position, habe ich das Problem mit "rein
regnen" nicht mehr.

Alles in allem! Respekt! Dafür hab ich auch gern nen "Zehner" gesendet und
werde das auch wieder in Erwägung ziehen! Ich bin gespannt, wie es weiter
geht!

Viele Grüße aus Nortorf (bei Kiel),
Markus

Am So., 28. Juli 2024 um 18:50 Uhr schrieb Herr.Vorragend <
***@***.***>:

**Comment by holsteiner-kiel** [comment]
Thank you very much! I sent you some information via Mail and didn't know that they are shown here. So I deleted them!

Thank you very much for your great Blueprint!
Markus

**Comment by hvorragend** [comment]
Was hast du gelöscht? 
Und was meinst du mit "via Mail"?

**Comment by holsteiner-kiel** [comment]
Sorry for that. I wrote you some information about my situation and a bit of smalltalk as answer to the notification. Is my first issue on github ;-) I wanted to send you that in a private message but there is no function for that :-)

All good! Long story short: Nice work! Thx alot!
