### ISSUE TITLE
define a tilt only open/ventilation/shading state not possible

### ISSUE THREAD

**Issue by olsen-sorensen** [hvorragend/ha-blueprints#121]
i want to define an open state only by setting the tilt position to 99% but got an error message, that the position must be greater than closed position. the same also for shading and ventilation...

**Comment by hvorragend** [comment]
I assume that your "normal" position specifications are all identical and only the slat values differ, right?

I didn't even take that into account in the config check. 

To be honest, I haven't questioned for weeks whether the check is still useful at all. You could simply deactivate the config check.

On the other hand, I will also comment out the code for now.
