### ISSUE TITLE
"Manual Override" don't work ?

### ISSUE THREAD

**Issue by hankys** [hvorragend/ha-blueprints#122]
Hello,
i'm still having problems with "Manual Override".

- "Sun Shading Brightness Start Value" is set to 20000 lx in the automation.
- "Sun Shading Position" is 20%
- "Ignore/override next automatic sun shading after manual position changes" ist selected.
- Reset at a specified time (see below) is set to 00:01:00

Today at about 15:00 I manually changed the shutter position to 40%, while brightness was still below 20000 lx.
At about 16:00 the brigtness went over 20000 lx, and the automation started shading, moved the shutter to 20%.

As far as i understand, the automation for shading should be ignored based on my configuration ?

**Comment by hvorragend** [comment]
The error was known, but did not yet exist as a ticket. There were already some posts about it in the forum. But thank you very much.

I have already fixed the error (once again). Update coming soon.
