### ISSUE TITLE
Automation terminates in the middle

### ISSUE THREAD

**Issue by prior-philip** [hvorragend/ha-blueprints#127]
Since a two days the CCA aborts after 3 steps. Havent changed anything to the logic - just duplicated the cca for another Rollershutter. Both, original and duplicate, shows same behavior.
Version in use 2024.07.06 & updated to 2024.08.03

![image](https://github.com/user-attachments/assets/5f86a8ce-afad-4974-9560-1b0573397c64)

> id: '1722965045508'
alias: Rollershutter Diningroom CCA
description: Opens/Close on Sun elevation
action: []
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.rollershutter_eg_terrace_diningroom
    drive_time: 20
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_sun_enabled
    open_tilt_position: 20
    close_tilt_position: 20
    shading_position: 20
    shading_tilt_position: 20
    time_up_early: '07:30:00'
    time_up_early_non_workday: '08:30:00'
    check_config: true
    auto_up_condition: []
    auto_down_condition: []
    time_down_late: '21:30:00'
    time_down_late_non_workday: '21:00:00'
    position_tolerance: 5
    sun_elevation_up: 34
    time_up_late: '08:30:00'
    time_up_late_non_workday: '09:30:00'
    time_down_early: '17:30:00'
    time_down_early_non_workday: '17:30:00'
    ventilate_tilt_position: 20
    ventilate_position: 20
    reset_override_config: reset_disabled
    time_schedule_helper: schedule.rollershutter_scheduler
    time_control: time_control_schedule
    default_sun_sensor: sun.sun
    drive_delay_random: 30
    drive_delay_fix: 5
    sun_elevation_down: 0
trace:
  stored_traces: 20

What could cause the issue? Any information missing to dive into the problem?

**Comment by hvorragend** [comment]
Could it be that you are using a beta of Home Assistant Core?

Then take a look here: https://github.com/hvorragend/ha-blueprints/issues/125#issuecomment-2272174912

**Comment by prior-philip** [comment]
Yepp, its beta...

**Comment by fisch55** [comment]
Same here …. Hope Theo will fix it…..

**Comment by hvorragend** [comment]
As far as I can see from the pull request, this has already been fixed and should no longer occur in the latest betas.

**Comment by fisch55** [comment]
Unfortunately, it still does not work in 2024.08b7.
Same problem as before....
Can I delete everything from the helpers so that it is empty. Will it then be refilled?

![Uploading Bildschirmfoto 2024-08-07 um 13.38.59.png…]()

**Comment by hvorragend** [comment]
Did you re-download the blueprint afterwards? The core has migrated something incorrectly. It probably needs to be renewed afterwards.

**Comment by hvorragend** [comment]
Refs https://github.com/home-assistant/frontend/pull/21599

**Comment by fisch55** [comment]
Updateing to .08b. 
After that I will redownload the BP.

**Comment by fisch55** [comment]
Does not help to reimport the BP...

**Comment by fisch55** [comment]
deleting the action: [] part in the BP ...WORKS BIG THX
