### ISSUE TITLE
Sun shading end without delay Settings

### ISSUE THREAD

**Issue by ChristianSill** [hvorragend/ha-blueprints#128]
I have noticed that when the shade option is ended, all the shutters go up at the same time without taking the delay into account. As a result, the roller shutters do not raise sporadically due to interference.

Can the delay times also be used when the shading function is ended?

Thank you very much

**Comment by hvorragend** [comment]
I will implement it.

**Comment by hvorragend** [comment]
Fixed in 2024.09.04
