### ISSUE TITLE
When residents are leaving, covers are always opened completely instead of their designated state

### ISSUE THREAD

**Issue by fsedarkalex** [hvorragend/ha-blueprints#129]
#115 was fixed but now covers always open completely, even if their designated state should be shading.

What I mean is, if there waws no resident, the cover would be in "shading" state. As there is a resident, the cover is actually still closed.
When the resident leaves, the cover does not switch to "shading" but to "open".

**Comment by fsedarkalex** [comment]
This is probably related to #126

**Comment by erobert-c** [comment]
Hello, and first of all thanks for the blueprint !

If I may add on this one, having a kid who goes to nap twice a day, having a way to go back to shading after the nap would be great. To give a bit more details on the complete scenario:
- blind is opened when the sun rise ✅ 
- shading starts, goes down ✅ 
- Nap time comes, the resident flag is turned on and the blind goes down as expected ✅ 
- End of the nap, resident flag goes off. 
- The blind is opened fully, and no shading occurs anymore after that ❌

If you prefer that I opened a dedicated ticket I can, but I have the feeling that is linked to this one.

Thanks.

**Comment by hvorragend** [comment]
Please try the new update 2024.09.04.

**Comment by hvorragend** [comment]
The resident function does not have the full scope of the ventilation or shading function. The resident feature is kept quite simple. On and off and nothing more. No reloading of any Rollo trips. No integration into the (I'll call it) state machine. 

The feature will not be expanded any further. Sorry.
