### ISSUE TITLE
Lockout protection possible?

### ISSUE THREAD

**Issue by MrMaxy21** [hvorragend/ha-blueprints#13]
Hi,
how can I set up a lockout protection for my patio door?
I would like to integrate this is an essential feature of such a door and I don't want to set up any faked vacation boolean helper.
Regards,
Lars

**Comment by hvorragend** [comment]
Did you read the description from the field "Cover Belongs To"? Isn't that what you're looking for?

**Comment by MrMaxy21** [comment]
Thank you for the quick response.
The setting for "Cover belongs to" is set to "Door", but the cover doesn't close, even if the door ist closed.
I'm not sure how the automation 'knows" whether the status of a door is closed.

**Comment by hvorragend** [comment]
There are various options.
You can use the conditions to prevent the roller blinds from closing. However, you cannot use this to make up for the closing.

Then there is the ventilation feature. This includes lock-out protection. This is perhaps an unfortunate description, as you don't actually want to ventilate. Is ventilation active for you?

**Comment by MrMaxy21** [comment]
I just activated the ventilation option.
But I guess my next issue is the door sensor I'm using.
This is the three-state window handle sensors HmIP-SRH from Homematic. The output of this sensor is not just 'open' or 'closed' and therefore not showing up in the drop-down list of a possible 'Contact Sensor Entity'. It is simply not a binary sensor.

**Comment by crandler** [comment]
> I just activated the ventilation option. But I guess my next issue is the door sensor I'm using. This is the three-state window handle sensors HmIP-SRH from Homematic. The output of this sensor is not just 'open' or 'closed' and therefore not showing up in the drop-down list of a possible 'Contact Sensor Entity'. It is simply not a binary sensor.

Create a helper for that:
`  - binary_sensor:
      - name: HmIP-SRH
        device_class: door
        state: >
          {{ is_state('sensor.HmIP-SRH', "tilted") or is_state('sensor.HmIP-SRH', "open") }}`

HmIP-SRH = your entity name

**Comment by MrMaxy21** [comment]
Thanks for the hint.
I add this to the configuration YAML and I'll give it a try tomorrow.
