### ISSUE TITLE
After reset manual - what should happen?

### ISSUE THREAD

**Issue by fisch55** [hvorragend/ha-blueprints#134]
After manual has been set back to false, the awning should close again at the next azimuth change, since the value is within azimuth start and aszimuth end?

`Wechselte zu {"open":{"a":false,"t":1724164447},"close":{"a":false,"t":0},"ventilate":{"a":false,"t":0},"shading":{"a":false,"t":1724164447},"locked":{"a":false,"t":0},"manual":{"a":false,"t":1724164741},"p":100,"v":4,"t":1724164741} ausgelöst durch Automatisierung Cover Control Markise Beta  ausgelöst durch Zeit change or manual update via template
16:39:00 - Vor 12 Sekunden

Wechselte zu {"open":{"a":false,"t":1724164447},"close":{"a":false,"t":0},"ventilate":{"a":false,"t":0},"shading":{"a":false,"t":1724164447},"locked":{"a":false,"t":0},"manual":{"a":true,"t":1724164632},"p":100,"v":4,"t":1724164632} ausgelöst durch Automatisierung Cover Control Markise Beta  ausgelöst durch Zustand von Markise
16:37:12 - Vor 3 Minuten`

However, shadowing remains on false after the reset manual, although azimuth triggers again and the other values still apply.

**Comment by fisch55** [comment]
alias: Cover Control Markise Beta
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation_beta.yaml
  input:
    blind: cover.markise
    auto_options:
      - auto_shading_enabled
    cover_status_helper: input_text.cover_helper_markise_beta
    shading_position: 0
    shading_tilt_position: 0
    time_control: time_control_disabled
    shading_brightness_sensor: sensor.wetterstation_warema
    shading_azimuth_start: 241
    shading_azimuth_end: 250
    shading_temperatur_sensor1: sensor.gw1000a_v1_7_6_indoor_temperature
    shading_min_temperatur1: 21
    shading_forecast_sensor: weather.home
    shading_forecast_temp: 21
    shading_waitingtime_start: 120
    shading_waitingtime_end: 120
    reset_override_config: reset_timeout
    reset_override_timeout: 1
    ignore_after_manual_config:
      - ignore_shading_after_manual
    auto_shading_start_condition:
      - condition: state
        entity_id: sensor.season
        state: summer
    auto_shading_end_condition: []
    auto_shading_end_action:
      - action: cover.open_cover
        metadata: {}
        data: {}
        target:
          device_id: bf53ef562020f767fa047aee6f101422
    check_config: true
    shading_temperatur_sensor2: sensor.gw1000a_v1_7_6_outdoor_temperature
    shading_min_temperatur2: 20
    shading_forecast_type: weather_attributes
    drive_time: 60
    cover_status_options: cover_helper_enabled
    reset_override_time: []

**Comment by hvorragend** [comment]
Nothing is done other than resetting the manual detection.

No shutter movement or similar is performed.
And no check is made as to whether anything should have happened during this time.

This function will not exist in CCA.

You have to wait for the next trigger.

**Comment by fisch55** [comment]
Accurate and next trigger is, for example, that the height of the sun changes, or the brightness - correct...
