### ISSUE TITLE
Shutter is fully closed by resident function while windows is tilted

### ISSUE THREAD

**Issue by holsteiner-kiel** [hvorragend/ha-blueprints#136]
If windows is tilted and the resident sensor goes to “on” with activated option for “Automatic closing due to the resident sensor”, the cover is closing completely.

Instead of this, it should go to the ventilation position because the window is tilted.
[trace automation.cca_schlafzimmer_beta 2024-09-01T12_34_22.906810+00_00.json](https://github.com/user-attachments/files/16828945/trace.automation.cca_schlafzimmer_beta.2024-09-01T12_34_22.906810%2B00_00.json)

**Comment by hvorragend** [comment]
Vielen Dank für den Hinweis. 

Kann es sein, dass du mir den falschen Trace zugeschickt hast? Das ist ein Trace zum Öffnen eines Rollos.

**Comment by hvorragend** [comment]
I have now checked this briefly.

A lot has changed in the latest beta updates since the version of 21 August. I am of the opinion that the error should not actually occur.

Even with Resisdent=On, the blind moves to the ventilation position.

Could you please test the latest beta?

**Comment by holsteiner-kiel** [comment]
You are right: here is the correct trace:
[trace automation.cca_schlafzimmer_beta 2024-09-01T16_12_51.918675+00_00.json](https://github.com/user-attachments/files/16829705/trace.automation.cca_schlafzimmer_beta.2024-09-01T16_12_51.918675%2B00_00.json)

I reproduced it again. Same: Shutter is closed completely.

**Comment by hvorragend** [comment]
You have deactivated your Cover Status Helper. 
This is required. This is why it is cancelled.

**Comment by holsteiner-kiel** [comment]
Thank you very much. Sorry for that!

Unfortunetely I cant't test again before friday :(
