### ISSUE TITLE
Shutter up after resident on not functional

### ISSUE THREAD

**Issue by holsteiner-kiel** [hvorragend/ha-blueprints#139]
Hi,

today I changed my automations from the old ones from August to the newest from yesterday. After the resident boolean changed from on to off (nobody sleeping anymore), the shutter is not opening in daytime. I think it was functional in the August versions.

Thx alot for your work!

[trace automation.cca_schlafzimmer_beta 2024-09-06T15_25_56.359780+00_00.json](https://github.com/user-attachments/files/16910058/trace.automation.cca_schlafzimmer_beta.2024-09-06T15_25_56.359780%2B00_00.json)

**Comment by holsteiner-kiel** [comment]
> Today (after the night) it worked. Perhaps you have an Idea why it didn't Work Yesterday.

**Comment by hvorragend** [comment]
Oh dear, it seems to be the time of day.   
And I'm surprised that this hasn't been complained about before. 

It is only opened if it is before "time_down_early" (16:00 in your case).  

At the time, I had to set a time period for this and just took the earliest time for closing the blinds. 

I'll see if I can find a different solution.
