### ISSUE TITLE
Trigger Ventilation Mode when opening window and roller is at 0%

### ISSUE THREAD

**Issue by ps915** [hvorragend/ha-blueprints#140]
Moin Moin,

first of all, thanks for this awesome blueprint. I moved from FHEM to HA and trying to replicate my Smarthome Automations from FHEM to HA. 

Your blueprint helps a lot! One thing i miss, is my "active ventilation mode"?

In FHEM, i had an automation, that opens the roller shutter to 35%, when i open the corresponding window. It only goes to ventilation mode, when the roller shutter was closed (0%). 
When i close the window + the roller shutter is at 35%, it will close the roller shutter. 

We use this, to maintain privacy (roller at 35% is almost closed) but still get some air into the room! =)

Is this possible with your blueprint? If not, what would you integrate it?

Another Question: 

Is it somehow possible to calculate the hours/minutes until the roller will close in the evening and will open in the morning. 
I want to show it next to the roller shutter control in the HA Dashboard

**Comment by hvorragend** [comment]
1) You could try the force features to activate the ventilation mode. 

2) I can't display a time because I don't know in advance when it will be triggered. I should be able to look into the future.
