### ISSUE TITLE
Shutter is fully closed after resident changes to „home“

### ISSUE THREAD

**Issue by factory42** [hvorragend/ha-blueprints#143]
See title. This is a new issue with the newest version.

Same behavior with different shutters and residents. This is a new issue with the current version. Did not happen in the past.

[trace automation.jalousie_simon_steuerung 2024-09-12T16_22_43.057777+00_00.json](https://github.com/user-attachments/files/16982889/trace.automation.jalousie_simon_steuerung.2024-09-12T16_22_43.057777%2B00_00.json)

[Shutter.yaml.txt](https://github.com/user-attachments/files/16982991/Shutter.yaml.txt)

**Comment by hvorragend** [comment]
Do you know that "resident_closing_enabled" is enabled in your config?

**Comment by factory42** [comment]
Yes. I am aware of that.

I thought that this would close the shutter at the given times and brightness values. But it closes the shutter now at any time when the resident arrives.

**Comment by hvorragend** [comment]
![Uploading IMG_4545.jpeg…]()

**Comment by hvorragend** [comment]
Yes, to the best of my knowledge it still exists 

I have only made it additionally possible to prevent the blinds from closing via a resident

**Comment by factory42** [comment]
OK. I give it a try without this option.

**Comment by factory42** [comment]
> OK. I give it a try without this option.

Works. 

Sorry, I was confused with the options.
