### ISSUE TITLE
Although a brightness Sensor is configured, cover shuts at "drive down - late..." 

### ISSUE THREAD

**Issue by el-Presi** [hvorragend/ha-blueprints#146]
Hi Guys,

maybe (I hope so, but I dont find it) I'm missing something, but my covers are all just driving down at the "Time for drive down - late..." time.
I also configured to drive down at "0 lx" brightness (after 180sec.), but this is not happening... Any ideas?

Thanks so far!!

![image](https://github.com/user-attachments/assets/ecf4476c-773a-446c-baa6-7f82e6e6ea63)

> 
alias: Schlafzimmer-Roll-Süd
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.schlafzimmer_rolladen_sud
    cover_status_options: cover_helper_enabled
    cover_status_helper: input_text.schlafzimmer_roll_sud_helper
    shading_position: 100
    reset_override_timeout: 0
    workday_sensor: binary_sensor.workday_sensor
    workday_sensor_tomorrow: binary_sensor.workday_tomorrow
    time_up_early: "07:30:00"
    time_up_early_non_workday: "09:00:00"
    time_up_late: "09:30:00"
    time_up_late_non_workday: "10:00:00"
    time_down_early_non_workday: "16:00:00"
    time_down_late: "22:00:00"
    time_down_late_non_workday: "22:00:00"
    default_brightness_sensor: sensor.hue_outdoor_motion_sensor_2_illuminance
    brightness_time_duration: 180
    brightness_up: 70
    sun_elevation_down: 0
    sun_elevation_up: 0
    drive_delay_random: 1
    shading_sun_brightness_start: 5000
    shading_sun_brightness_end: 4500
    shading_azimuth_start: 120
    shading_azimuth_end: 200
    shading_weather_conditions:
      - sunny
      - partlycloudy
      - clear
    shading_forecast_sensor: weather.forecast_home
    shading_forecast_type: hourly
    shading_forecast_temp: 26
    shading_brightness_sensor: sensor.wettersensor_beleuchtungsstarke
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_brightness_enabled
      - auto_ventilate_enabled
      - auto_shading_enabled
      - auto_lockout_protection_enabled
    contact_sensor: binary_sensor.fenster_gekippt_f_rolladenautom
    ventilate_position: 13
    contact_sensor_lockout: binary_sensor.schlafzimmer_fenstersensor_tur_2
    check_config: false
<

**Comment by el-Presi** [comment]
Maybe I see the issue by myself...:

When I compare it to other automations (with this blueprint):

When I put the lower brightness value in the GUI to "5" it is shown in the YAML, when I put it to "0" it is not shown in YAML (and so maybe not executed?)

**Comment by hvorragend** [comment]
Please update your blueprint. 
Could be related with https://github.com/hvorragend/ha-blueprints/issues/144

It was fixes in v2024.09.19

**Comment by hvorragend** [comment]
> Maybe I see the issue by myself...:
> 
> When I compare it to other automations (with this blueprint):
> 
> When I put the lower brightness value in the GUI to "5" it is shown in the YAML, when I put it to "0" it is not shown in YAML (and so maybe not executed?)

Default values (and 0 is the default value) are Not saved in the YAML Condor.
