### ISSUE TITLE
Ventilation Mode Not working anymore in 2024.09.19

### ISSUE THREAD

**Issue by el-Presi** [hvorragend/ha-blueprints#147]
Hi!
I have several Covers, at none of them, the ventilation mode is working anymore since the update to 2024.09.19.
The automation is not triggered by the assigned binary sensor.

**Comment by hvorragend** [comment]
Please show me your config. 
Or do you perhaps even have a trace?

And are you sure that the contact sensors have been reconfigured (see Breaking Change)?

**Comment by el-Presi** [comment]
Ok... my fault - its working fine, after updating the binary sensors :D Sorry!

**Comment by hvorragend** [comment]
Thanks for your feedback.
