### ISSUE TITLE
Ventilation level and closing after ventilation

### ISSUE THREAD

**Issue by EckeFL** [hvorragend/ha-blueprints#150]
Hi,
version 2024.09.25 seems to have a ventilation problem.

When the ventilation is triggered, the cover open to 100% instead of the setted level. 
Tilt and open have the same behaviour. 

Closing after ventilation doesn't work.
The covers don't move.

I'm using HM-LC-Bl1PBU-FM for the covers.
Before I used Version 2024.08.2X without problems.

Best regards
EckeFL

**Comment by hvorragend** [comment]
My guess is that your contact sensors are incorrectly stored in the CCA blueprint. It was the same in all previous posts. 
Can you show me your YAML?

**Comment by EckeFL** [comment]
Shure. 
`alias: Rollladen Automation Schlafzimmer
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    default_brightness_sensor: sensor.helligkeit
    contact_sensor: binary_sensor.fenster_schlafzimmer_beide
    individual_config: []
    blind: cover.rollladen_schlafzimmer
    cover_status_helper: input_text.schlafzimmer_roll_level_helper
    check_config: true
    brightness_up: 100
    brightness_down: 130
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_brightness_enabled
      - auto_sun_enabled
      - auto_ventilate_enabled
    cover_status_options: cover_helper_enabled
    shading_position: 31
    ventilate_position: 67
    drive_time: 22
    workday_sensor: binary_sensor.workday_sensor
    time_up_early_non_workday: "09:00:00"
    time_up_late_non_workday: "10:00:00"
    time_up_late: "07:00:00"
    contact_window_opened: binary_sensor.fenster_schlafzimmer_beide
    lockout_tilted_options: []
    auto_ventilate_options:
      - ventilation_if_lower_enabled`

Thats the template of _binary_sensor.fenster_schlafzimmer_beide_
`{% set b1 = states('binary_sensor.fenster_schlafzimmer_r_state') %}
        {% set b2 = states('binary_sensor.fenster_schlafzimmer_l_state') %}
        {% if b1 == 'on' and b2 == 'on' %} on
        {% elif b1 == 'off' and b2 == 'on' %} on
        {% elif b2 == 'off' and b1 == 'on' %} on
        {% elif b2 == 'off' and b1 == 'off' %} off
        {% elif b1 == 'unavailable' or b2 == 'unavailable' %} unavailable
        {% else %}  unbekannt
        {% endif %}`

`alias: Rolladen Küche
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.rolladen_kuche_rollladen_kuche
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_brightness_enabled
      - auto_sun_enabled
      - auto_ventilate_enabled
    cover_status_helper: input_text.helperlevelrolladenkuche
    drive_time: 19
    ventilate_position: 100
    workday_sensor: binary_sensor.workday_sensor
    time_up_early_non_workday: "08:00:00"
    time_up_late_non_workday: "09:00:00"
    default_brightness_sensor: sensor.bewegungsmelder_hof_brightness_2
    brightness_up: 150
    brightness_down: 130
    contact_window_opened: binary_sensor.helperwindowopenkuche
    contact_window_tilted: binary_sensor.helperwindowtiltkuche
    cover_status_options: cover_helper_enabled
    tilt_delay: 2
    auto_ventilate_options:
      - ventilation_delay_enabled`

**Comment by hvorragend** [comment]
Ich verstehe deine drei verschiedenen Configs nicht. Es ist doch augenscheinlich erkennbar, dass diese unterschiedlich sind.

Es sind auch alte Parameter für die Kontaktsensoren vorhanden. Überprüfe bitte eine Konfiguration und wirf bitte einen Blick auf das Changelog. Dort - und auch im Forum - ist die Änderung beschrieben. 

Und was meinst du mit "tilt detection"? Du meinst das gekippte Fenster und nicht die Lamellen, oder? Die zweite Config sieht nämlich eigentlich ganz gut aus. Wenn das nichts mit den Konktaktsensoren zu tun hat, dann erstelle bitte ein eigenes Ticket. 

Vielen Dank und Grüße

**Comment by EckeFL** [comment]
Hallo, entschuldige die Verzögerung.
Den Changelog hatte ich tatsächlich übersehen. Sorry. Dann sind die anderen beiden Configs natürlich irrelevant.

Zur zweiten Config.

Ja ich meine mit "tilt detection" das gekippte Fenster. Als Sensor nutze ich dafür einen Homematic Drehgriffsensor. 
Für die Helper nutzte ich folgendes Template, natürlich mit "open" oder mit "tilted" 
```
{{ is_state('sensor.fenster_kuche_state_2', "tilted") }}
```

Die Helper habe ich gecheckt. "open" ist "off" wenn des Fenster gekippt ist und umgekehrt.
Schließen "Schließen nach dem Lüften" als auch die "Tilt Position" funktionieren werden nicht angefahren.
Kann ich bei der Fehleranalyse noch unterstützen oder einfach für die Übersichtlichkeit ein neues Ticket erstellen?

Grüße

**Comment by hvorragend** [comment]
Im Anbetracht des Tickets https://github.com/hvorragend/ha-blueprints/issues/153 kann ich dieses dann nun schließen, oder?
