### ISSUE TITLE
Add an Option to open the shutters completely like the ventilation mode

### ISSUE THREAD

**Issue by N3331N** [hvorragend/ha-blueprints#151]
Hi, Feature request ☺️

I would love to see an second option for opening the shutters within ur blueprint.

- First mode is the already implemented ventilation mode, which (in my case) trigger when the windows/doors are „gekippt“ and set the shutters to 30 percent.

- Second mode should (in my case) open the shutters completely when the windows/doors are opened widely. And of course the shutters should be closed when the window/door is closed again. Let’s call it ventilation mode 2 😂

thanks

**Comment by crandler** [comment]
You should update your blueprint version. ;-)

**Comment by N3331N** [comment]
Nice. Can u give me a hint which option is able to do that?

**Comment by crandler** [comment]
Contact Sensors for Ventilation
 - 🚪 Contact Sensor For Open Window (Full Ventilation)
 - 💨 Contact Sensor For Tilted Window (Partial Ventilation)

**Comment by hvorragend** [comment]
I'm just sitting back here and watching the goings-on. 😀

In the update, which was released more than a month ago, it was pointed out in the changelog and also in the forum that there are changes. Everything is described there. 
An old configuration of the contacts must be revised.
