### ISSUE TITLE
Improvement: clearer titles/descriptions on new options

### ISSUE THREAD

**Issue by fsedarkalex** [hvorragend/ha-blueprints#158]
I found the new labeblin a bit irritating.

Example: For resident settings, the descriptions says
![image](https://github.com/user-attachments/assets/9286071f-0d0f-44d3-9638-5014467646e5)
so for me expected behavior with no checkbox set is, that sensor = true closes and sensor=false opens the blind if it should be open based on other triggers.

reading further the options say...
![image](https://github.com/user-attachments/assets/d01502f0-413e-48f5-89c6-1d91442e0d32)

Does this now mean I need to CHECK this box to make the cover close? Or does it mean it disables the automatic closing?

Same for other options as well.

This might seem clear to you as you know then backgrounds, but for me the labeling is not clear on what does exactly what.

**Comment by hvorragend** [comment]
Done in v2024.12.20: https://github.com/hvorragend/ha-blueprints/commit/5c6b535cd6dbcd08eb8e88aef82f1c416cf1f012
