### ISSUE TITLE
Force Features Enhancement

### ISSUE THREAD

**Issue by Skol6** [hvorragend/ha-blueprints#159]
Hi,
under the point "Additional Conditions" it is posible to set multipe entities and/or conditions.
BUT: those are not tiggered

under Force Features a trigger of only one entity can be added.
BUT: I would like to enter multiple conditions. f.e. snow, rain AND wind trigger.

Is it possible to adopt the Force Features similar to the Additional Conditions, so that multiple condititons can be used?

Btw. I have changed from Iobroker to HomeAssistant. In IObroker there is a simila plugin called Shutter Control, maybe you finde some additional ideas for your integration - https://github.com/simatec/ioBroker.shuttercontrol/wiki/Shuttercontrol-Wiki-Deutsch

thanks!

**Comment by hvorragend** [comment]
Ich gehe mal davon aus, dass du die deutsche Sprache sprichst, wenn du auch aufs deutsche ioBroker-Wiki verlinkst.

Bedingungen in HA können nicht triggern. Es wird beim Verarbeiten anderer Trigger nur zusätzlich geprüft, ob diese individuelle Bedingung erfüllt ist.

Beim Force-Feature kann nur ein Boolean angegeben werden. Es steht dir aber frei, den Inhalte deines Boolean-Helpers für dich individuell zu steuern. Entweder über Templates oder Automationen.

Ich habe aber auch im Hinterkopf, dass es in HA neuerdings auch möglich sein wird, Trigger zu individualisieren. Das wird irgendwann kommen. Siehe #157
