### ISSUE TITLE
Feature Request: Add Wind Protection for Electric External Venetian Blind

### ISSUE THREAD

**Issue by Gounick** [hvorragend/ha-blueprints#161]
#### Description

The current blueprint for managing covers ([Electric External Venetian Blind)](https://www.somfy.co.uk/products/electric-external-venetian-blinds/) is effective in handling sun position and cover adjustments. However, Electric External Venetian Blind are particularly vulnerable to damage during wind storms or strong gusts of wind. To mitigate this risk, it is essential to add functionality that **automatically opens the Electric External Venetian Blind when the wind speed exceeds a specified threshold**.

#### Proposed Solution

Modify the blueprint to include:
1. **Wind Sensor Input**: A sensor entity capable of measuring wind speed (e.g., km/h).
2. **Wind Speed Threshold**: A configurable value where, if exceeded, the Electric External Venetian Blind will open automatically to prevent potential damage (default to 60 km/h in gust).
3. **Automated Opening Action**: Ensure that if the wind speed exceeds the threshold, the covers are immediately opened.
4. **Auto Restore to Previous State**: Ensure that if the wind speed falls below the threshold, the covers return to their previous state.

#### Additional Notes

This feature is critical for regions prone to high winds and storms. Adding this capability enhances the resilience and usability of the blueprint for users managing Electric External Venetian Blind.

Let me know if you need further details for this enhancement.

**Comment by hvorragend** [comment]
I have built in the force functions for this purpose. Then each individual query can be taken into account.
