### ISSUE TITLE
Trigger on status change of (Additional condition for the entire automation)

### ISSUE THREAD

**Issue by flyboy1** [hvorragend/ha-blueprints#17]
Hi hvorragend

I use the additional conditions true/false to completely deactivate the automatic shutter function in certain situations. 

It would be great if the automation would trigger after a status change of the additional conditions (e.g. off to on) to move to the correct shutter position.

Thank you for your time and great work.
flyboy1

**Comment by hvorragend** [comment]
Please have a look here:
https://community.home-assistant.io/t/blueprint-condition-selector-as-trigger/684557

I really need this, too. 
But it doesn't seem to be possible. At least I can't do that.

**Comment by hvorragend** [comment]
Refs #8

**Comment by hvorragend** [comment]
Sorry, not possible in HA.
