### ISSUE TITLE
today() vs today_at()

### ISSUE THREAD

**Issue by crandler** [hvorragend/ha-blueprints#2]
In debugging section you use function today() which doesn't exist:
see https://github.com/hvorragend/ha-blueprints/blob/14efeeb1edf85ab8ab214b5963625ebcfe2190c0/blueprints/automation/cover_control_automation.yaml#L1461 and following.

**Comment by hvorragend** [comment]
Thank you. Fixed now with f2d60c7bec8ce55f0905414d7c8446e776b38e67
