### ISSUE TITLE
Dynamic adjustment of the slat position

### ISSUE THREAD

**Issue by Tarzipan** [hvorragend/ha-blueprints#27]
It would be great if the shading function could be extended so that the slats are only closed far enough based on the position of the sun so that no sunlight gets inside but you can still look outside.

I have already used such a function in another system and this blueprint can probably be adapted quickly.

https://knx-user-forum.de/forum/projektforen/edomi/994915-lbs-19000145-beschattungssteuerung-ng

The code there is written in PHP.

Many thanks

**Comment by hvorragend** [comment]
Please see closed issue: 
https://github.com/hvorragend/ha-blueprints/issues/3
