### ISSUE TITLE
[Feature Request] Frost protection (or: auto_ventilate_force)

### ISSUE THREAD

**Issue by Kurisutian** [hvorragend/ha-blueprints#28]
Currently looking into this blueprint to migrate my shutter automation away from NodeRed to HA internal I found only one thing missing: Frost protection

I have some aluminum shutter on some glass roof and noticed that even with the slightest temperatures below zero it tends to freeze and gets stuck when opening. So in order to protect the motor from having to stop by itself I thought it would be nice to have some sort of option to set temperatures when the shutter should not be opened. This could also be more generic allowing to also define a higher temperature when it should remain down (eg. if a night was already >21°C it's expected to be more hot during the day so the shutter should not open at all; however protecting the motor when the shutter froze seems to me the more important case).

It would be great to have something like that build in as an selectable option to select a sensor and temperature when to prevent from opening. 

Thanks in advance and thanks for the awesome blueprint!

**Comment by Elle4u** [comment]
Hi,

I support this feature request.

But in my case I had implemented it a bit different:
My "Frost Protection" was implemented like "is frost on?" (Sensor, for example <1°C) then put the shutter to ventilation position.
So the shutter was not completly closed and could not frost.
The opening at the morning was never again a problem. :-)

**Comment by hvorragend** [comment]
The problem here is the high level of customisation. And that's exactly why I added the ForceUp and ForceDown functions a few days ago.
I deliberately mentioned "Frost Protection" in the description. We had already talked about this in the forum.

**Comment by hvorragend** [comment]
By the way. Your requirements can also be easily implemented with the additional conditions in the blueprint.

**Comment by Elle4u** [comment]
I can build a template group for each shutter with "or" on both sensors (window open, frost on) and use this for the ventilation function if there is no way to implement a second sensor. ;)

**Comment by hvorragend** [comment]
Do I understand you correctly? 
In addition to auto_up_force and auto_down_force, would an auto_ventilate_force help you? That would be a good option.
