### ISSUE TITLE
Lockout protection and ventilation mode should have different sensors (And maybe 2 of them)

### ISSUE THREAD

**Issue by himisk2022** [hvorragend/ha-blueprints#31]
Hi.

_

> 🚪💨 Contact Sensor Entity
> The contact sensor is required for lock-out protection and for ventilation mode. It must be a binary two-way contact sensor.
> Lock-out protection:
> The roller blind is not closed if the door contact is on or true.
> Ventilation mode:
> If the door contact changes to on/true, the roller blind is moved to the ventilation position. After the status changes to off/false, the close position is activated. The same applies in the shading-out situation.

_

1) I have a room with 2 windows with 1 common roller blind. so i need 2 sensors for monitoring, am i right?

2) i have another room with a balkony door. for lockout protection i take the sensor for the door handle. but when i use this, it will close the blind to my ventilation high (20%).

is it possible to separate these two cases, one sensor for lockout and one for ventilation? and 2 input options for sensors for ventilation? but i could create a group, so it is not so important..

**Comment by hvorragend** [comment]
1) I would really prefer it if you put both contacts in one group. 

2) I'm not sure about this. That could be a very good idea. But I still have to form an opinion on it. The problem is that I also need to ensure some kind of backwards compatibility.

**Comment by fsedarkalex** [comment]
I seconds the seperated sensors. I am actually using this kind of setup.

I have a window contact to detect an open door (used for ventilation, heating and security) and a handle sensor which I am using for lockout protection.

Why? There is a very good reason to that:
On a hot summer day, you want to keep the door closed to keep hot air out. But you still want to get back inside, so the door (contact) is closed while the handle is in open position.

**Comment by hvorragend** [comment]
Good point

**Comment by hvorragend** [comment]
Current branch for this: https://github.com/hvorragend/ha-blueprints/tree/separated_contacts

**Comment by hvorragend** [comment]
Added now in https://github.com/hvorragend/ha-blueprints/pull/62
