### ISSUE TITLE
Suggestion: Improve Structure on GUI

### ISSUE THREAD

**Issue by Bostil87** [hvorragend/ha-blueprints#36]
Currently it is not easy to orientate on all different settings. Would it be possible to re-order by category and add header-titles for the diff. Segments ?

E. G. Combine sub-protection (azimuth, elevation, temperatures) in one segment and add a header to it.

Thanks for the great work !!!

**Comment by hvorragend** [comment]
Yes, it is extensive and therefore difficult to find the right place. 

But I have absolutely no structuring options.

For this reason, I have deliberately separated the areas using emojis.

There's no other way.
