### ISSUE TITLE
Description for "Additional Condition For Opening The Cover" doesn't make sense

### ISSUE THREAD

**Issue by naKruul** [hvorragend/ha-blueprints#37]
The description says:

"With this condition you can prevent the automation from opening the cover. You can use this, for example, if the covers normally don't open, but you really want to do it on vacation."

So what does the condition do, if it is met? Will it  make the cover go up or does it stay down? 

e.g. what will happen with the following condition?
![image](https://github.com/hvorragend/ha-blueprints/assets/40398952/89fd2245-755a-4168-9f21-8b5822e963ff)

**Comment by hvorragend** [comment]
Hello, you should really update your system. I already changed this many many days ago.
