### ISSUE TITLE
Allow controlling a input_boolean helper as entity

### ISSUE THREAD

**Issue by maia** [hvorragend/ha-blueprints#45]
I'd like to use the blueprint to control a input_boolean helper. Unfortunately this isn't possible at the moment, it isn't available in the list of entities in the blueprint.

The reason for this wish is that I'm controlling multiple Velux shades via the Velux Gateway (Homekit), connected to Apple Home since 2022. When I attempted to remove them from Apple Home and readd them in HA last year, I ran into major issues. 

I therefore decided to keep the shades with Apple Home and instead expose `input_boolean.blinds_target_state` from HA to Apple Home via Homekit Bridge. In Apple Home I have a simple automation that will open/close all shades based on the state of this exposed helper.

Is there any way to adapt the blueprint to allow controlling `input_boolean`as entity? Thanks!

**Comment by hvorragend** [comment]
Yes, you can use the additional actions to toggle your booleans.

**Comment by maia** [comment]
I don‘t understand. I currently cannot use the CCA blueprint to control my input_boolean that controls my blinds: 
![IMG_6999](https://github.com/hvorragend/ha-blueprints/assets/9836/f2be3de7-0f05-4d2b-97f7-625c41597236)

**Comment by hvorragend** [comment]
On second thought, it makes more sense to fork my blueprint. There's no way I can allow anything other than the cover domain here. 

But feel free to take my blueprint and modify it.

**Comment by maia** [comment]
Thanks! I found the following in the code and will look into how to create a "fake" entity in HA that allows a 0-100% range and can be used to control the blinds. Besides that I will ask Velux on when they will support Matter on their KIG 300 gateway (which might have been bundled with a sensor and is now sold as KIX 300).

```
selector:
        entity:
          filter:
            - domain:
                - cover
```
