### ISSUE TITLE
Force shading feature?

### ISSUE THREAD

**Issue by hvorragend** [hvorragend/ha-blueprints#46]
Force shading feature?

**Comment by DNC74** [comment]
First, thanks a lot for that great blueprint! 
I had exact the same idea already to open a feature request: 
- shading start on demand by a button press or another automation
- shading end on demand by a button press or another automation

I would really appreciate that feature.
Thanks again!

**Comment by hvorragend** [comment]
I have programmed it so far and could upload it soon. However, I noticed that "Force Deactivating Sun Shading" makes no sense at all. Because the blinds are only opened. This also works with the "Force Up" feature. 

So I'll leave it out and only include activating the shading. 

Do you agree?

**Comment by hvorragend** [comment]
Already implemented.
