### ISSUE TITLE
Feature Request: Close windows again after ventilation.

### ISSUE THREAD

**Issue by LHBL2003** [hvorragend/ha-blueprints#49]
The roller blind was closed. I opened the window. The ventilation function opened the roller blind by 30%.
Now I have closed the window again, but the roller blind does not lower again.
I have not seen a function to activate this.

Expected behavior:
Move to the position as it should be after ventilation.

**Comment by hvorragend** [comment]
Strange. But that's how it should already be. 
Can you please show me a trace?

**Comment by LHBL2003** [comment]
Stange is that it now works. :D
However, I also installed the latest version yesterday. Perhaps there was an overlap.

Thanks anyway ;)
And keep up the good work ;)
Thanks for the Blueprint.

**Comment by LHBL2003** [comment]
I just remembered that I had set the "Position Tolerance" from 0% to 5% last night in bed. Because the window was stopped at 38% instead of 40%. I'm sure that's what made it work now. I had subconsciously set the tolerance yesterday because I had read about it a long time ago.
