### ISSUE TITLE
Centralize config

### ISSUE THREAD

**Issue by fsedarkalex** [hvorragend/ha-blueprints#50]
Hi! I really like your blueprint, it is a great piece of code!

I will be using it on several windows and I wonder if it would e possible to pull out some common configuration to a central helper.
I am thinking about hings like light levels, temperature tresholds elevation tresholds...

Imagine a house with 6 windows into one direction, you'd have to set up 6 individual configurations and change 6 configs for any change.

Or maybe it would be possible to contorl multiple windows with one CCA instance while keeping the control on a per shutter basis (I mean that CCA doesn't get confused as it would with a group today)

**Comment by hvorragend** [comment]
This request has been made to me several times. I would like that too. But that's not possible in HA. 

I would like to refer to outsourced helpers. But how? Then I would have to convert everything into text fields if necessary. No more sliders or similar. 

And debugging would be a disaster. 

If I see an approach in HA at some point, I will implement it directly. 

The problem with the groups is that each one can have a different position and therefore the group has an average value in the "current_position" attribute. 

It's even possible to work with groups. This is already taken into account in many places. But most users had problems with it.

**Comment by fsedarkalex** [comment]
Thanks for the clarification.
Can you resolve groups in HA? So you could treat each shutter individually while only having one instance?
Or use a multi entity input?

**Comment by hvorragend** [comment]
I'll take a look at the others. 

I'm just afraid that this will make it even more complex. But let's see.

**Comment by hvorragend** [comment]
I'm sorry, but I've decided against it. I currently have tons of redundant code and can't encapsulate within an HA blueprint. 

By resolving the groups, I would have to integrate many loops and many additional conditions. 

Also, I have only ever saved one status in the Cover Status Helper. I might have to extend the JSON helper and will have problems with the 254 character limit. 

Without a flash of inspiration or elementary code changes, I don't want to tackle the issue at the moment.
