### ISSUE TITLE
Include Wind-Sensor

### ISSUE THREAD

**Issue by Hexcodes** [hvorragend/ha-blueprints#51]
Hey,

at my mothers house I have some wind sensitive covers which need to be opened when the wind is to strong.
I was trying to achieve this by setting the "Force Open" option with a boolean sensor, but it seems that the automation is not going  back to normal operation after the sensor is set to "false" again.

For example if it was closed (at night) beforehand it stays now open until the rest of the night.

Is there a way to achieve this with this somehow? If not would be great to have this option in an future version.

Kind regards

**Comment by hvorragend** [comment]
The blueprint can't do that and you have to get a handle on it with your own automations. 

The blueprint cannot know what has happened in the meantime.
