### ISSUE TITLE
brightness_down wouldn't be saved

### ISSUE THREAD

**Issue by Pauli29** [hvorragend/ha-blueprints#54]
The value for brightness_down wouldn't be saved.

here the trace of my configuration

id: '1713551064226'
alias: Rollladen-Bar
description: ''
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.bar_rollladen
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_brightness_enabled
    open_position: 100
    time_up_early: '07:00:00'
    time_up_early_non_workday: '07:15:00'
    time_up_late: '07:30:00'
    time_up_late_non_workday: '07:45:00'
    close_position: 0
    default_brightness_sensor: sensor.hmip_swo_pl_00181be9a427de_beleuchtungsstarke
    brightness_up: 10
    check_config: true
    workday_sensor: binary_sensor.workday_sensor
    cover_status_options: cover_helper_enabled
    cover_status_helper: input_text.rl_bar
    brightness_down: 1

**Comment by hvorragend** [comment]
The entire code indentation is missing here. Therefore, I would guess that you have either inserted the YAML code incorrectly or have changed the blueprint config manually. So nothing fits here.

**Comment by Pauli29** [comment]
I only installed your blueprint and create a new automation.
I just try again but the yaml code exactly is the same.
it only include the brihtness_up

**Comment by hvorragend** [comment]
Please put your YAML into code tags. 

It should look like this:

```
- id: '1706121706616'
  alias: Rollo - EG - Diele
  description: ''
  trace:
    stored_traces: 20
  use_blueprint:
    path: hvorragend/cover_control_automation.yaml
    input:
      blind: cover.diele
      auto_global_condition:
      - condition: state
        entity_id: input_boolean.auto_rollo_eg
        state: 'on'
      workday_sensor: binary_sensor.workday_today
      drive_delay_fix: 80
      time_up_early: 07:15:00
      time_up_early_non_workday: 07:45:00
      time_up_late: 08:15:00
      time_down_early: '16:30:00'
      default_brightness_sensor: sensor.lichtsensoren
      brightness_up: 50
      brightness_down: 120
      sun_elevation_up: 4
      sun_elevation_down: -1
      cover_status_options: cover_helper_enabled
      cover_status_helper: input_text.rollo_status_diele
      auto_shading_options: auto_shading_enabled
      auto_shading_start_condition:
      - condition: state
        entity_id: input_boolean.auto_shading_rollo
        state: 'on'
      auto_shading_end_condition:
      - condition: state
        entity_id: input_boolean.auto_shading_rollo
        state: 'on'
      shading_sun_brightness_start: 41000
      shading_sun_brightness_end: 35000
      shading_azimuth_start: 275
      shading_azimuth_end: 360
      shading_elevation_min: 5
      shading_min_temperatur1: 21
      shading_min_temperatur2: 22
      shading_temperatur_sensor1: sensor.innen_temperature_filtered
      shading_temperatur_sensor2: sensor.aussen_temperature_filtered
      shading_forecast_sensor: weather.openweathermap
      shading_forecast_temp: 20
      auto_options:
      - auto_up_enabled
      - auto_brightness_enabled
      - auto_down_enabled
      - auto_sun_enabled
      - auto_shading_enabled
      shading_brightness_sensor: sensor.lichtsensor_westen_filter_moving_average
      time_down_early_non_workday: '16:30:00'
      time_down_late_non_workday: '22:30:00'
      time_up_late_non_workday: 08:30:00

```

**Comment by hvorragend** [comment]
Or show me a screenshot of the yaml code.

**Comment by Pauli29** [comment]
all other defined options work fine

**Comment by hvorragend** [comment]
I can tell you for sure that the value 1 works.

**Comment by Pauli29** [comment]
this is the yaml

`
alias: Rollladen-Bar
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.bar_rollladen
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_brightness_enabled
    open_position: 100
    time_up_early: "07:00:00"
    time_up_early_non_workday: "07:15:00"
    time_up_late: "07:30:00"
    time_up_late_non_workday: "07:45:00"
    close_position: 0
    default_brightness_sensor: sensor.hmip_swo_pl_00181be9a427de_beleuchtungsstarke
    brightness_up: 10
    check_config: true
    workday_sensor: binary_sensor.workday_sensor
    cover_status_options: cover_helper_enabled
    cover_status_helper: input_text.rl_bar
    brightness_down: 1

`

**Comment by Pauli29** [comment]
`alias: Rollladen-Bar
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.bar_rollladen
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_brightness_enabled
    open_position: 100
    time_up_early: "07:00:00"
    time_up_early_non_workday: "07:15:00"
    time_up_late: "07:30:00"
    time_up_late_non_workday: "07:45:00"
    close_position: 0
    default_brightness_sensor: sensor.hmip_swo_pl_00181be9a427de_beleuchtungsstarke
    brightness_up: 10
    check_config: true
    workday_sensor: binary_sensor.workday_sensor
    cover_status_options: cover_helper_enabled
    cover_status_helper: input_text.rl_bar
    brightness_down: 1
`

**Comment by Pauli29** [comment]
`alias: Rollladen-Bar
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.bar_rollladen
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_brightness_enabled
    open_position: 100
    time_up_early: "07:00:00"
    time_up_early_non_workday: "07:15:00"
    time_up_late: "07:30:00"
    time_up_late_non_workday: "07:45:00"
    close_position: 0
    default_brightness_sensor: sensor.hmip_swo_pl_00181be9a427de_beleuchtungsstarke
    brightness_up: 10
    check_config: true
    workday_sensor: binary_sensor.workday_sensor
    cover_status_options: cover_helper_enabled
    cover_status_helper: input_text.rl_bar
    brightness_down: 1
`

**Comment by Pauli29** [comment]
I am sorry I don't know why the code tags do  not work :-(

**Comment by hvorragend** [comment]
Screenshot?

**Comment by Pauli29** [comment]
![Screenshot 2024-05-12 220410](https://github.com/hvorragend/ha-blueprints/assets/71097725/363effee-96eb-470f-96c6-ccbfebe52687)

**Comment by Pauli29** [comment]
I just saw now it contains the value :-)
Could it be that the value has to be > 0 ?

**Comment by hvorragend** [comment]
I can't find any errors. 
Yes, the slider only allows steps of 10. 
But manual entries are still saved. 

I can remove the step size in the next version. Then the input field at 1 is not marked red. 

But it should still work.

**Comment by Pauli29** [comment]
This is no problem.
But when I insert 0 as value the option will be deactivated.
This was not clear for me.
Thank you for your time.

**Comment by hvorragend** [comment]
No, this is not deactivated with 0.
