### ISSUE TITLE
Brightness options do not work 

### ISSUE THREAD

**Issue by Pauli29** [hvorragend/ha-blueprints#56]
The values for open and close are in the configuration but don't work :-(

**Comment by Pauli29** [comment]
![Screenshot 2024-05-15 202933](https://github.com/hvorragend/ha-blueprints/assets/71097725/e74d9424-dfbd-4ba3-b3d8-ec6f07ab6cd8)

**Comment by hvorragend** [comment]
Related with #54

**Comment by hvorragend** [comment]
Why? How can you tell?
The screenshot looks okay. 
What exactly is not working?
What do you expect?
What should happen?
Do you have a trace?

Could it be that you are waiting for the numeric trigger? Are you aware of how the triggers work in HA? That the threshold must be exceeded?

**Comment by Pauli29** [comment]
Yes sorry for opening a new topic.
Now the values were saved but don't work and I not find  the error .
Because the sensor changed to 0 but the cover did not close

**Comment by hvorragend** [comment]
Are you using the newest version from today?

Looks like there is still a bug in the current version. I also have the problem that the blinds don't go down

**Comment by hvorragend** [comment]
Please update now to v2024.05.15-02

**Comment by Pauli29** [comment]
You were right this was the error.
I am very new in HA.
If I set the value for closing to 0,1 it works.
Thank you very much!

**Comment by hvorragend** [comment]
Thanks for the tip.
I was wondering at exactly the same moment why my own blinds weren't closed yet. :-)
