### ISSUE TITLE
Tilt on covers via a script

### ISSUE THREAD

**Issue by lejmr** [hvorragend/ha-blueprints#57]
This is a great blueprint!

I am pretty green into HA, but I have several shellyies that I am using for controlling external shades that I would like to tilt, but Shelly 2PM, which I am using, does not have support for tilt at the moment.

I found an article about tackling tilt-faking https://medium.com/@lukasvice/a-utility-script-for-controlling-venetian-blinds-with-shelly-in-home-assistant-2e5cbf2d8d5f

If I understand it well, the article suggests creating a script `script.cover_position_tilt`, which is equivalent to `cover.set_position_tilt`. Would it be possible to externalize how tilt is called in your blueprint? If I am right, it would let me tilt my shades via your blueprint! 

Thanks

**Comment by hvorragend** [comment]
![IMG_2829](https://github.com/hvorragend/ha-blueprints/assets/343705/5b5ecbcd-2f42-4cd6-9d9b-d7269cd069ed)

you can use additional actions and disable the default actions.
