### ISSUE TITLE
Shading activates when door is open - goes to wrong position after manual re-open

### ISSUE THREAD

**Issue by fsedarkalex** [hvorragend/ha-blueprints#58]
Version: 2024.04.08-01

Today I was sitting on my terrace, the door opened (contact in correct state) but the shutter tried to go to shading position anyways.

I noticed it and stopped the motor, sending it to open position again using the local controls on the actor (HMIP-BROLL-2 if relevant).
The actor sent the new position to HA so it was aware, that the shutter is fully opened again.

The shutter did not close again this day.

When shading ended, the said one wrongly went to ventilate position instead of open.
I will open a second issue for that as I beliave this is not related. Just noting this here in case it matters.

**Comment by hvorragend** [comment]
Please take a look on the changelog and update your blueprint. 

https://github.com/hvorragend/ha-blueprints/blob/main/blueprints/automation/CHANGELOG.md
