### ISSUE TITLE
Shutter goes to ventialte instead of open after shading

### ISSUE THREAD

**Issue by fsedarkalex** [hvorragend/ha-blueprints#59]
Version: 2024.04.08-01

Today, I was sitting on my terrace so I had the door open, shutter opened completely while all other shutters were in shading mode.
Worth to note, as described in #58 , I manually sent it to open after it closed to shading position (it never reached the shading level).

When shading ended this day, the said one wrongly went to ventilate position instead of fully open (the door was open).

**Comment by hvorragend** [comment]
Same answer as #58 
Please Update your blueprint and try again.

**Comment by fsedarkalex** [comment]
> Same answer as #58 Please Update your blueprint and try again.

damn! I totally overlooked there were updates to the main blueprint. Sorry!
