### ISSUE TITLE
Individual opening and closing times

### ISSUE THREAD

**Issue by hvorragend** [hvorragend/ha-blueprints#6]
Posted in the community thread:

> If you allow I would like to ask if it is possible to add a more sophisticated calendar for individual opening and closing times. More like individual programmes per day.

> Hi Herr.Vorragend, well, the work shift schedule might change or be different per weekday. Or pupils have later school on certain days.
So it would be great if it would be possible to open the rollers e.g. on Monday, Wednesday and Friday at 6:30am, on Tuesday at 7:30 and on Thursday at 8:15. On Saturday and Sunday at 9:00 (or dependent on the sun elevation). Same for closing during the weekdays at 22:30 but on weekends on 23:15.

**Comment by spelzl** [comment]
Please refer to issue #9

**Comment by hvorragend** [comment]
Duplicate
