### ISSUE TITLE
Covers opened at night

### ISSUE THREAD

**Issue by fsedarkalex** [hvorragend/ha-blueprints#60]
I am currrently on latest version.

Tonight at 3:00 my bedroom cover opened "for no reason" (Window closed, earliest open time is way later, it was dark outside)

I examined this and I found out that many sensors seem to have reinitialized at this time. 
Also I noticed that ALL CCAs have been triggered and CCA has sent a command to all of them . 

Examinig this deeper it seems the door contacts went to "not_available" or "none" because of  this reinitialization - could have been a technical issue in zigbee2mqtt.
So the state change to "none" or "not_initialized" (depending on the integration) seems to have triggered CCA's ventilation mode.

I would expect CCA to ignore these states (don't do any action caused by sensors in these states)

![image](https://github.com/hvorragend/ha-blueprints/assets/16449266/28d8c785-5991-4df7-bb58-08cb9113f788)

**Comment by fsedarkalex** [comment]
seems there is also "unknown" as a possible value

**Comment by fsedarkalex** [comment]
Okay I just notiec that the issue of opening cover is caused by a defective sensor. For some reason it is wrongly repoting "open" for a closed window.

BUT anyways the state change has still triggered alls CCAs, but the others seem to have sent the correct command (closed in this case)
Proabably you would still want to check this, so I am keeping the case open

**Comment by hvorragend** [comment]
Thank you. Will be fixed in the next update. 
See commit in branch "separated_contacts": https://github.com/hvorragend/ha-blueprints/commit/7c088b50ae4d38664cf9deddf4b475eee899ce26

**Comment by hvorragend** [comment]
Fixed in https://github.com/hvorragend/ha-blueprints/pull/62
