### ISSUE TITLE
Feature Request: Disable AutoClose in Resident Mode

### ISSUE THREAD

**Issue by fsedarkalex** [hvorragend/ha-blueprints#63]
Me again 😂

I don't know if that was suggested or thought about before, but I was wondering if it would be much work to add a checkbox to "individual configuration" which disables the auto-close of the cover when resident switches to on?

To explain my usecase/what I would like to achieve:
My girlfriend is working in shifts and sometimes she sleeps longer, sometimes shorter so I want the cover to delay opening until nobody is in the bedroom for some time - the "for some time" is possible in my presence sensor so no problem here.

But I simply don't want the covers to close everytime someone walks in the room

If there is another way to achieve this, let me know please.
I was thinking about preconditions for opening instead of resident mode, but this would mean I have to manually open the cover (because the automatic open is not delayed but skipped in this case) if I understand this right.

**Comment by hvorragend** [comment]
Now already added in the branch for the next major release.

**Comment by hvorragend** [comment]
Danke, fsedarkalex.  Hab gerade 'was bekommen. :-)

**Comment by fsedarkalex** [comment]
Gerne :) Ich danke dir, dass du mir Tagelange Tüftelarbeit abgenommen hast!

**Comment by hvorragend** [comment]
Solved with https://github.com/hvorragend/ha-blueprints/pull/68
