### ISSUE TITLE
"Force Close" does not work when "Condition For Closing" is true

### ISSUE THREAD

**Issue by truefoobar** [hvorragend/ha-blueprints#64]
"Force Close" does not work when "Condition For Closing" is true.
If you set the condition to false, then force close works with true.

Version: 2024.05.22-01

**Comment by hvorragend** [comment]
That would be strange. There are absolutely no conditions that are checked in the force-close area. 

See:
https://github.com/hvorragend/ha-blueprints/blob/main/blueprints/automation/cover_control_automation.yaml#L2942

**Comment by truefoobar** [comment]
is my situation possible when this switch is set?

_...
Additional condition for the entire automation
This condition allows you to control the execution of the entire automation dynamically and outside of the blueprint configuration. With this option you could enable a party mode.
..._
