### ISSUE TITLE
Feature Request: additional sensor for Ventilation2/Opening

### ISSUE THREAD

**Issue by crandler** [hvorragend/ha-blueprints#67]
My suggestion: an additional sensor that can operate as "Ventilation2" respectively "Opening".

This would allow the implementation of a terrace door handle or comparable sensor so that when in tilt position, the roller shutter can be set to the slotted position or the blinds to a horizontal position, and when the door handle is in open position, the shutter or blinds autmatically open to allow access to the terrace. When sensor closed, go back to CCA's calculated position.

As long as one sensor is active, neither shading nor closing should affect the blinds, which corresponds to the lock-out protection. 

Extra lock-out protection can then be removed.

**Comment by crandler** [comment]
#73

**Comment by hvorragend** [comment]
Ich diskutiere auch gerade mit dem User darkm242, der ähnliche Anforderungen hat.

Nehme wir mal an, wir führen den 3-Wege-Griff (Dreh+Kipp+Offen - oder wie die heißen) ein.
Input Sensor 1 =Griff gekippt = Lüften
Input Sensor 2 = Griff geöffnet = Hochfahren

Wie gehe ich mit den Anwendern um, die nur die Lockout-Protection nutzen?

Nicht jeder möchte vielleicht, dass das Rollo sich dann öffnet.
Wobei es von Anfang an sicherlich logischer gewesen wäre, wenn ich es direkt so umgesetzt hätte. :-)

Brauche ich wirklich eine weitere Checkbox (Rollo nicht öffnen, wenn Input Sensor 2 geöffnet wird?)

**Comment by jmerifjKriwe** [comment]
Die Lockout-Protection war initial ja nur eine einfache Lösung, um das Runterfahren bei offener Tür zu verhindern. Glaube, die wurde einfach nicht zu Ende gedacht. Insofern wäre es aus meiner Sicht nur zu Ende gedacht, wenn die beim Öffnen des Kontaktes auch öffnet. Wobei dann aber natürlich die Frage ist, ob das 100% oder z.B. auch 75% (und Limbo-tanzend unter dem Rollo durch raus gehen) sein können. Insofern macht ein weiterer Wert dafür vermutlich Sinn.

**Comment by hvorragend** [comment]
Fixed in version 2024.09.04.
