### ISSUE TITLE
[Feature Request] Implementation Suggestion: Recovering from force open/close

### ISSUE THREAD

**Issue by philippk80** [hvorragend/ha-blueprints#69]
Hello :)
Wouldn't it be possible to recover from force states?
I tried to check your code and maybe I'm wrong. 
If not I could maybe contribute that.

- [ ] Add a bit in status helper for each force (for example: forceOpen)
- [ ] Only set the force bit in status helper (other vars should not be changed)
- [ ] Remove all cover moving code from all choose branches
- [ ] Remove all force switches from all branches
- [ ] At the end of blueprint: implement a logic that recognizes the target position from the status helper and then moves the covers

If I'm not wrong the automation will then proceed to fill the status helper with the target position even when forcing.
So if we set the force to false we can recover to status helper state.
Maybe there are a lot of details missing which prevent to do that.
I hope for some input there. (Gerne auch auf Deutsch falls das einfacher ist) You know your code the best. :)

**Comment by hvorragend** [comment]
Hey, du bist ja ganz pfiffig. Der Code ist ziemlich voll geworden. Das gefällt mir aktuell auch überhaupt nicht. 

Bei der letzten großen Änderung hatte ich mir verschiedene Vorgehensweise aufgeschrieben und bin die Vor- und Nachteile durchgegangen. 

Mein Plan war ähnlich. Ich würde eine Art Hintergrundprozess laufen lassen, der die Soll-Werte schreibt. Und darauf soll der gleiche Blueprint dann reagieren und die Ist-Umsetzung durchführen. Ähnlich wie bei der Erkennung von manuellen Fahrten. 
Anfangs war ich begeistert von der Idee. Doch im Support wird das eine Katastrophe. Ich brauche von den Nutzern dann jedesmal mehrere Traces. Einmal fürs Soll. Und einmal für die Exekutive. 

Jetzt will ich den Blueprint erst einmal reifen lassen. Neue Features müssen erst einmal warten.

**Comment by philippk80** [comment]
Danke für deine Ausführliche Antwort. Immer gut wenn man unabhängig voneinander zu einer ähnlichen Lösung kommt. :)
Verstehe ich das richtig das auch contribute davon nicht erwünscht wäre?

Bei mir sind im Haus alle Rollläden mit einem Schalter ausgestattet der zwischen Force Up, Force Down oder Auto umschaltet. Mit der Besonderheit das die Lüftungsfunktion auch bei Force-Down gibt. (Einen Schlafmodus hab ich bei meinem Smarthome wieder zurückgebaut) 
Somit würde nach einem Force der Status bis zum nächsten Trigger eingefroren bleiben.
Das hält mich aktuell ab den Blueprint zu nutzen. Vielleicht übersehe ich aber auch einfach nur eine Konfigurationsmöglichkeit die mir das möglich macht.

**Comment by hvorragend** [comment]
> Verstehe ich das richtig das auch ein contribute davon nicht erwünscht wäre?

Nee, nix ist unerwünscht. Ganz im Gegenteil. 
Aber eine Änderung dieser Art dürfte den gesamten Code auf links drehen. Und ich muss diesen dann in Forum supporten. 
Bock hätte ich schon darauf, aber das wird IMHO ein übelst komplexer Pull Request. 

Eigentlich dürfte CCQ kein Blueprint mehr sein. Als eigene Integration wie "Adaptive Cover" wäre es mittlerweile vermutlich der richtigere Weg. Ich will mit Abstraktionsebenen, Funktionen etc.  arbeiten. Und den Code eleganter machen. 
Nur kann ich nicht wirklich gut Python programmieren. Und PyScript oder AppDaemon-Addons sind auch nur andere Wege zum Ziel in gleicher Sprache. 

> Das hält mich aktuell ab den Blueprint zu nutzen. 

Das habe ich nicht genau verstanden. Was hindert dich?

**Comment by hvorragend** [comment]
> * [ ]  Add a bit in status helper for each force (for example: forceOpen)
> * [ ]  Only set the force bit in status helper (other vars should not be changed)
> * [ ]  Remove all cover moving code from all choose branches
> * [ ]  Remove all force switches from all branches
> * [ ]  At the end of blueprint: implement a logic that recognizes the target position from the status helper and then moves the covers
> 


Kleine Anmerkung dazu. 
In einem HA-Blueprint kannst du nicht wirklich gut linear programmieren bzw. du kannst keine globalen Variabeln zur Laufzeit setzen. Jeder Paramter hat in Jinja2 seinen kleine eigenen Scope. Nur mit namespace kommt man ein wenig weiter. 

Ich kann also nicht am Ende prüfen, was ich zur Laufzeit herausgefunden habe. Ich kann halt nur etwas in einem Helper schreiben und darauf per Trigger reagieren. 
Und dann sind wir wieder bei der Vielzahl an Traces, die ich im Support benötige.

**Comment by philippk80** [comment]
Ich musste heute fertig werden deshalb habe ich mich dazu entschieden erstmal meine eigene Suppe zu kochen. Das wird dir wenig für deinen Blueprint helfen aber ich konnte die komplette Ableitung des Zielstatis von den angegeben Entities (ohne Helper Objekt) berechnen. D.h. jedes mal wenn ich den Blueprint aufrufe (auch bei einem manuellen Aufruf) rechnet er den korrekt Zielstatus aus. Das funktioniert bei aber nur weil ich bei mir Zuhause keine manuelle Positionierung außerhalb des Blueprints erlaube.

**Comment by hvorragend** [comment]
Vielen Dank für die Unterhaltung.
Ich behalte das mal in Erinnerung. Aber aktuell ist diesbezüglich (insbesondere nach dem letzten großen Umbau) nichts in Planung. Daher schließe ich das Ticket erst einmal.
