### ISSUE TITLE
"Feature Request:" adding feature

### ISSUE THREAD

**Issue by yazend** [hvorragend/ha-blueprints#70]
Thank you in advance for your work so far.
Basically, your blueprint works with my "Somfy RTS" roller shutters because they don't have a feedback system and you can also trigger them manually, which cannot be recorded via Home Assistant (not without great effort and expense).
I sometimes miss the position where the roller shutters are currently located, here the function of a reference run (complete up or down) would be desirable.
It would also be desirable if you could call up scenes instead of entity(s).
Again, this is due to multiple calls which are sent to a kind of queue in Home Assistant, but "HA" cannot process more than 10 at the same time. In my case, there are 37 roller shutters which often cannot be addressed one after the other because the queue is already full. Working with delays doesn't improve this noticeably either, but calling up scenes instead of the individual roller shutters prevents this.
Perhaps it is worth considering implementing this on your part.
Thank you in advance
BR yazend

Vielen Dank schon mal für deine bisherige Arbeit.
Grundsätzlich funktioniert dein Bauplan mit meinen „Somfy RTS“ Rollläden, da diese kein Feedbacksystem haben und man diese auch manuell auslösen kann, was sich über Home Assistant nicht (nicht ohne großen Aufwand) erfassen lässt.
Mir fehlt manchmal die Position, wo sich die Rollläden gerade befinden, hier wäre die Funktion einer Referenzfahrt (komplett hoch oder runter) wünschenswert.
Wünschenswert wäre auch, wenn man Szenen statt Entity(s) aufrufen könnte. Auch hier liegt das an Mehrfachaufrufen, die in eine Art Warteschlange im Home Assistant gehen, „HA“ aber nicht mehr als 10 gleichzeitig verarbeiten kann.
Bei mir sind es 37 Rollläden, die oft nicht nacheinander angesprochen werden können, da die Warteschlange schon voll ist.
Auch das Arbeiten mit Verzögerungen verbessert das nicht merklich, aber das Aufrufen von Szenen statt der einzelnen Rollläden verhindert das.
Vielleicht ist es eine Überlegung wert, dies von deiner Seite aus umzusetzen.
Vielen Dank schon mal
Gruß yazend

**Comment by hvorragend** [comment]
Hallo, du erwartest ziemlich viel von einem Blueprint. Eigentlich sollte Home Assistant bzw.  die Integration viele diese Dinger bereits abnehmen. Ich kann in einem Blueprint nicht alles das versuchen umzusetzen, was eine Integration nicht kann. 

Der Blueprint funktioniert leider ausschließlich mit der Cover-Domain. Vor allen Dingen auch, weil die Befehle ausschließlich bei _Covers_ funktionieren.

Wichtig ist zudem, dass ich eine Entität habe, die ein Positionsattribut besitzt. Das ist auch der Grund, wieso ich hier keine Szenen nehmen kann.

Sorry, aber die meisten Punkte müssen woanders geklärt werden und nicht in CCA.
