### ISSUE TITLE
Three-way contact sensors

### ISSUE THREAD

**Issue by hvorragend** [hvorragend/ha-blueprints#73]
- Tilt = move to ventilation
- Contact open = move to open

**Comment by jmerifjKriwe** [comment]
But keep in mind that currently you can define two different sensors for ventilation and blockout protection.
So it could be possible that both show different states due to different reaction time of the Sensor (or hardware protocol). You have to check for any race conditions :-/

**Comment by hvorragend** [comment]
Fixed in version 2024.09.04.
