### ISSUE TITLE
Make it configurable in which situation the ventilation mode can be executed

### ISSUE THREAD

**Issue by hvorragend** [hvorragend/ha-blueprints#75]
Make it configurable in which situation the ventilation mode can be executed

**Comment by darkman242** [comment]
and that the roller blind only moves to the position for ventilation when the roller blind is already closed?!

**Comment by hvorragend** [comment]
There were a few errors that have been fixed here: https://github.com/hvorragend/ha-blueprints/commit/875cd42e14ab2b99d6e07b2be3dab0651c7b59c0

This currently leaves only the following ventilation options:

- When closing the blinds (now works again)
- When the window contact is opened
- When ventilation is forced

Ventilation is no longer activated after the sun protection is ended. Or does someone need this and I can make it configurable? But then I need an explanation of why this is important.

Translated with DeepL.com (free version)
