### ISSUE TITLE
Feature Request: Add "Additional Actions Before X"

### ISSUE THREAD

**Issue by alorle** [hvorragend/ha-blueprints#77]
I would be great if the automation can perform some actions before something happens: for example, announce that the cover is closing or send a notification.

I'm scaring my wife to death every time the covers come down by themselves without a warning... XD

And by the way, great job with the blueprint, thanks for all the hard work!!

**Comment by hvorragend** [comment]
I find that a little difficult. I would have to revise countless code passages. And at the moment it looks to me like a one-off request. You are welcome to fork my code and add your own code. But at the moment I don't really want to do that.

I have to pay a little attention to the users and also be able to provide support. And I can't fulfill every individual wish. I'm sorry.

**Comment by alorle** [comment]
Totally understandable.  I'll try what you say, since I think it may need some more customization so it won't hurt.  Thanks in any case!!

**Comment by fbloemhof** [comment]
+1 for this request, for what it's worth.
