### ISSUE TITLE
Cover-move by Sensor 

### ISSUE THREAD

**Issue by Pauli29** [hvorragend/ha-blueprints#78]
Is it possible that 
1.
when the cover was closed by the blueprint and the sensor changes the cover drives automatically.
2.
When the cover díd not close because of lockout-protection, that it closes as soon as the sensor changes.

**Comment by hvorragend** [comment]
I'm sorry. I don't quite understand that. Could you please explain this in more detail?

**Comment by Pauli29** [comment]
1. The brightness sensor reach the threshold but the cover does not close because of the state of the doorsensor (lockout-protection). But I want that the cover closes as soon as the door was closed.
2. When I open the door and the cover is closed by the automatic the cover should open and close again when I close the door

**Comment by hvorragend** [comment]
1. This should already work without any problems. 
2. It is a little different here. The ventilation position is reached when the contact is opened. I'm thinking about extending this at some point. Then it should open completely when the door is tilted to ventilation and when the door contact is opened. Refs #73
