### ISSUE TITLE
Zip-screen setup

### ISSUE THREAD

**Issue by BeFygo** [hvorragend/ha-blueprints#82]
Hi I'm trying to config your blueprint to work with my zip-screens but i cannot get it to work.

Every trigger results in '{{ check_config }}' with a direct 'stop' of the automation.

The zip-screens are partly transparent and what i expect is that when the sun azimut is higher than 95° and temperature in the room is above 21°C (time restricted) at day the screens close to 0%

When azimut is lower than 240° the screen opens to 100%

**Comment by hvorragend** [comment]
First of all: you cannot run the blueprint manually. I could imagine that you did that. 

At first I thought you had exactly the opposite requirements. But that doesn't seem to be the case. You should be able to implement this via the sunshade. Have you already tried this?

**Comment by hvorragend** [comment]
Then please show me a trace with the trigger "t_si_1" and I will check this.

**Comment by BeFygo** [comment]
[trace automation.katten_screen_cca 2024-06-26T07_37_46.117835+00_00.json](https://github.com/user-attachments/files/15992992/trace.automation.katten_screen_cca.2024-06-26T07_37_46.117835%2B00_00.json)
[trace automation.katten_screen_cca 2024-06-25T18_08_01.566329+00_00.json](https://github.com/user-attachments/files/15993112/trace.automation.katten_screen_cca.2024-06-25T18_08_01.566329%2B00_00.json)

The automation is running for some days now and nothing happens, several triggers but no actions.

**Comment by hvorragend** [comment]
Please take a look on the latest posts in this thread: https://community.home-assistant.io/t/cover-control-automation-cca-a-comprehensive-and-highly-configurable-roller-blind-blueprint/680539/779

There are some automation options missing. 
open/close is missing

**Comment by BeFygo** [comment]
That was it, i checked those off when troubleshooting the first time, probably because i manually ran the automation.
