### ISSUE TITLE
Suggestion: Limit Shading function to a defined date / period (e. g. 01.04. - 15.09.)

### ISSUE THREAD

**Issue by Bostil87** [hvorragend/ha-blueprints#85]
Just copying this idea from the Iobroker / ShutterControl, that I used before and think it could make sense: Lets imagine you can set a start and end-date for the Shading function.

Why, if we have already many conditional settings for activating the shading ?
- especially in spring (western Europe, e. g. until end of March) you will take the rare warmer days (> 19°) somewhen earlier the year to warm up the house and reduce heating costs as you most likely will await also some colders nights / days. At a certain period you will start activating sun shading as you need to defend for the sun over the summer period.

I totally reckon that this could be set via the existing conditional settings, but maybe it makes sense / is possible to set as a separate setting as this is an easier solution for beginners.

**Comment by hvorragend** [comment]
I would not like to introduce a separate setting for this. Why not do this - as suggested - via the additional conditions for sun protection?
