### ISSUE TITLE
Find a way to detect when the cover move in a manual position

### ISSUE THREAD

**Issue by Idaho947** [hvorragend/ha-blueprints#87]
I’m looking for a way to know when a manual action was done on the shutter, so when the shutter switches to manual mode.

I think that creating a switch-type helper that switches to off when the shutter is in manual mode is a good idea.

**Comment by hvorragend** [comment]
Do you think a feature "Additional Actions After Manual Change" can help you?

It is almost ready.

**Comment by Idaho947** [comment]
Yes i think it is a perfect way to do that!
