### ISSUE TITLE
flexibe weekday opening and closing time schedules

### ISSUE THREAD

**Issue by spelzl** [hvorragend/ha-blueprints#9]
Hi @hvorragend , **please refer to issue no 6...**
thank you for continuouing the work on the roller 
I'd like to propose to add weekday opening and closing time schedules.

Use Case: The work shift schedule might change or be different per weekday. Or pupils have later school on certain days.

Suggestion: So it would be great if it would be possible to open the rollers e.g. on Monday, Wednesday, Thursday and Friday at 6:45am, on Tuesday at 7:35am. On Saturday and Sunday at 9:05am (or dependent on the sun elevation?).

![image](https://github.com/hvorragend/ha-blueprints/assets/82170464/d932eb3b-773f-4355-9f64-853aae9ee467)

And the same for closing during the weekdays at 22:30 but on weekends on 23:15.

It'll be great if this could be added into the blueprint.
Thanks in advance
Kind regards

**Comment by hvorragend** [comment]
Posted in the community thread:

> If you allow I would like to ask if it is possible to add a more sophisticated calendar for individual opening and closing times. More like individual programmes per day.

> Hi Herr.Vorragend, well, the work shift schedule might change or be different per weekday. Or pupils have later school on certain days.
So it would be great if it would be possible to open the rollers e.g. on Monday, Wednesday and Friday at 6:30am, on Tuesday at 7:30 and on Thursday at 8:15. On Saturday and Sunday at 9:00 (or dependent on the sun elevation). Same for closing during the weekdays at 22:30 but on weekends on 23:15.

**Comment by hvorragend** [comment]
I could use the calendar integration for this and then open and close it via the calendar triggers.

To do this, you create an "open" appointment that opens at the start and closes again at the end.

But then there are no early/late times. And therefore perhaps also no sun or brightness control.

Would that be an idea?

Übersetzt mit DeepL (https://www.deepl.com/app/?utm_source=ios&utm_medium=app&utm_campaign=share-translation)

**Comment by spelzl** [comment]
I am afraid that many users of the blueprint as it is will be disappointed if the shading and ventilation features would not be available anymore after the integration of the calendar feature.

**Comment by hvorragend** [comment]
Shading and ventilation remain as before. But I can no longer open and close via the brightness or the height of the sun.

**Comment by spelzl** [comment]
Isn't shading dependent on the sun?

**Comment by hvorragend** [comment]
> Isn't shading dependent on the sun?

The changeover has nothing to do with the sun. I just have to do without a time frame. No Early. No late. And therefore no control via the height or brightness of the sun in between.

**Comment by hvorragend** [comment]
Another idea. Almost better than the HA Calendar: The new HA scheduler helper. 

![image](https://github.com/hvorragend/ha-blueprints/assets/343705/26040635-0993-4bf8-9ce4-28a312ab9a84)

**Comment by hvorragend** [comment]
Or we can use the calendar and create two time periods. One for opening and one for closing. For time periods, I can then also determine the start and end again and use the brightness and sun control.

![IMG_1498](https://github.com/hvorragend/ha-blueprints/assets/343705/d42e7417-f0cf-45e6-b751-50ac2b14ca6e)

**Comment by spelzl** [comment]
You are very creative and come up with excellent ideas.
What happens in this example between 16:30 and 22:00 when both (open & close) are true?

**Comment by hvorragend** [comment]
Oops. That was a fault.

**Comment by hvorragend** [comment]
Same here. But I need the beginning and the end of a time period. And that twice a day. 

And I need to have a way of recognizing what is for morning and evening.
Have a look at the states in the DEV tools. Then you'll understand me. Annoys me a little too.

**Comment by spelzl** [comment]
If the schedule helper would need to become a mandatory amendment would it be possible to 'simply' add default schedules all the same for opening in the mornings and closing in the evening so it won't cause trouble to those who don't need individual schedules?

**Comment by hvorragend** [comment]
Refs ecf708fb9a136273ba9380b313b7f13be4d3da75

**Comment by spelzl** [comment]
Fantastic!
I haven't expected this to be turned around that quickly.
Many thanks!
Very much appreciated!

I'll give it a go on the weekend and try it!
