### ISSUE TITLE
Perhaps also trigger shading cyclically?

### ISSUE THREAD

**Issue by hvorragend** [hvorragend/ha-blueprints#97]
Perhaps also trigger shading cyclically? Multiple requests, because otherwise the threshold values are not exceeded so often.

**Comment by JSchmid6** [comment]
Maybe you can fix manual triggering. So we can trigger a recheck of shading conditions externally. At the moment, manual triggering automation has no effect.

**Comment by hvorragend** [comment]
I don't necessarily have to trigger cyclically, it's also sufficient to trigger at every brightness value. 
But I don't really like that at all, because it can lead to countless CCA triggers. And my aim was always to avoid a lot of triggers.

**Comment by hvorragend** [comment]
[julian1712](https://community.home-assistant.io/u/julian1712)
(https://community.home-assistant.io/t/cover-control-automation-cca-a-comprehensive-and-highly-configurable-roller-blind-blueprint/680539/978?u=herr.vorragend)

> Hi,
> 
> I have a resident mode in my beedroom and an Sun Shading when azimuth is >100.
> When i am sleeping longer than the azimut >100 and i disable the resident mode, the cover will open, but won´t close again for shading since there is no azimuth > 100 trigger.
> 
> Is there any way to solve this?

**Comment by crandler** [comment]
Maybe you can add one helper variable to all triggers that activates all triggers at once when the value of the helper is updated. However, I'm not sure if this will fit into the CCA logic.

**Comment by hvorragend** [comment]
Please try the new version 2024.09.04.
